
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AUTO DIRECTIVE FAMILY IFACE INTERFACE_NAME IP_ADDRESS METHOD\ninterfaces : interface\n           | interfaces interface\n\ninterface : AUTO INTERFACE_NAME\n          | IFACE INTERFACE_NAME FAMILY METHOD config_lines\n\nconfig_lines : config_line\n            | config_lines config_line\nconfig_line : DIRECTIVE IP_ADDRESS'
    
_lr_action_items = {'AUTO':([0,1,2,5,6,10,11,13,14,],[3,3,-1,-2,-3,-4,-5,-6,-7,]),'IFACE':([0,1,2,5,6,10,11,13,14,],[4,4,-1,-2,-3,-4,-5,-6,-7,]),'$end':([1,2,5,6,10,11,13,14,],[0,-1,-2,-3,-4,-5,-6,-7,]),'INTERFACE_NAME':([3,4,],[6,7,]),'FAMILY':([7,],[8,]),'METHOD':([8,],[9,]),'DIRECTIVE':([9,10,11,13,14,],[12,12,-5,-6,-7,]),'IP_ADDRESS':([12,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'interfaces':([0,],[1,]),'interface':([0,1,],[2,5,]),'config_lines':([9,],[10,]),'config_line':([9,10,],[11,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> interfaces","S'",1,None,None,None),
  ('interfaces -> interface','interfaces',1,'p_interfaces','parser.py',6),
  ('interfaces -> interfaces interface','interfaces',2,'p_interfaces','parser.py',7),
  ('interface -> AUTO INTERFACE_NAME','interface',2,'p_interface','parser.py',16),
  ('interface -> IFACE INTERFACE_NAME FAMILY METHOD config_lines','interface',5,'p_interface','parser.py',17),
  ('config_lines -> config_line','config_lines',1,'p_config_lines','parser.py',26),
  ('config_lines -> config_lines config_line','config_lines',2,'p_config_lines','parser.py',27),
  ('config_line -> DIRECTIVE IP_ADDRESS','config_line',2,'p_config_line','parser.py',35),
]
