
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AUTO DIRECTIVE FAMILY IFACE INTERFACE IP METHOD NEWLINE\nconfig : config_item\n       | config config_item\n\nconfig_item : auto\n           | iface\nauto : AUTO INTERFACE NEWLINEiface : IFACE INTERFACE FAMILY METHOD NEWLINE directives\ndirectives : directive NEWLINE\n          | directives directive NEWLINE\ndirective : DIRECTIVE IP'
    
_lr_action_items = {'AUTO':([0,1,2,3,4,7,10,14,18,20,],[5,5,-1,-3,-4,-2,-5,-6,-7,-8,]),'IFACE':([0,1,2,3,4,7,10,14,18,20,],[6,6,-1,-3,-4,-2,-5,-6,-7,-8,]),'$end':([1,2,3,4,7,10,14,18,20,],[0,-1,-3,-4,-2,-5,-6,-7,-8,]),'INTERFACE':([5,6,],[8,9,]),'NEWLINE':([8,12,15,17,19,],[10,13,18,20,-9,]),'FAMILY':([9,],[11,]),'METHOD':([11,],[12,]),'DIRECTIVE':([13,14,18,20,],[16,16,-7,-8,]),'IP':([16,],[19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'config':([0,],[1,]),'config_item':([0,1,],[2,7,]),'auto':([0,1,],[3,3,]),'iface':([0,1,],[4,4,]),'directives':([13,],[14,]),'directive':([13,14,],[15,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> config","S'",1,None,None,None),
  ('config -> config_item','config',1,'p_config','parser.py',6),
  ('config -> config config_item','config',2,'p_config','parser.py',7),
  ('config_item -> auto','config_item',1,'p_config_item','parser.py',16),
  ('config_item -> iface','config_item',1,'p_config_item','parser.py',17),
  ('auto -> AUTO INTERFACE NEWLINE','auto',3,'p_auto','parser.py',22),
  ('iface -> IFACE INTERFACE FAMILY METHOD NEWLINE directives','iface',6,'p_iface','parser.py',26),
  ('directives -> directive NEWLINE','directives',2,'p_directives','parser.py',31),
  ('directives -> directives directive NEWLINE','directives',3,'p_directives','parser.py',32),
  ('directive -> DIRECTIVE IP','directive',2,'p_directive','parser.py',40),
]
